# Generated by Django 6.0.3 on 2026-03-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
