# Generated by Django 6.0.3 on 2026-03-11 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0003_mensaje_descripcion_mensaje_resuelto_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
