# Generated by Django 6.0.3 on 2026-03-11 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_contacto_delete_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(9, 'El teléfono debe tener al menos 9 caracteres.'), django.core.validators.RegexValidator('^[0-9+\\-\\s]+$', 'Solo se permiten números, espacios, + y -')]),
        ),
    ]
