# Generated by Django 6.0.3 on 2026-03-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_conversacionoculta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='ultima_lectura_usuario1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='ultima_lectura_usuario2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
